spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

springdoc:
  override-with-generic-response: false

server:
  port: 8080

scheduler:
  icd:
    cron: "0 0 0 * * *"

async:
  settings:
    icd:
      name: icd
      corePoolSize: 3
      maxPoolSize: 3
      queueCapacity: 100

sources:
  url:
    ICDs: https://github.com/ak4nv/mkb10/raw/refs/heads/master/mkb10.csv

batch:
  icd:
    size: 500

page:
  icd:
    size: 20